# Auto-generated from research-findings.md
# Do not edit — regenerate with convert-research-to-templates.py

RESEARCH_TEMPLATES = [
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Hi Tom, I don't think we should file the motion until we've reviewed the deposition transcripts, the expert reports and the interrogatory responses. FYI the deadline is next Friday so we need to move ASAP. Let me know what you think. Thanks, Mike""",
        "error_types": ['contraction', 'informal_language', 'missing_oxford_comma', 'vague_timeline'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """We've reviewed your client's demand and our client is willing to pay $75,000 to resolve this matter. Please confirm if your client accepts this offer.""",
        "error_types": ['subject_verb_agreement', 'ambiguity'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Per our conversation, I agree to the settlement terms discussed — $150,000 payment within 30 days, full release of all claims, dismissal with prejudice.""",
        "error_types": ['binding_language', 'subject_verb_agreement', 'modal_verb_error'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """As we discussed on the call, the client's records clearly show that your client breached the contract. We expect your client to remedy this immediately or we will proceed accordingly.""",
        "error_types": ['vague_timeline', 'overconfident', 'defined_term_issue', 'tone_adversarial'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Please be advised that pursuant to our client's rights under the agreement, they hereby demand that you cease and desist from the continued violation of Section 4.2. Govern yourself accordingly.""",
        "error_types": ['informal_language', 'legalese', 'throat_clearing', 'redundant_doublet', 'archaic_language', 'govern_yourself'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """I am writing to follow up on my previous email of March 3rd regarding the outstanding invoices. As I mentioned in that email, payment is overdue. Please remit payment at your earliest convenience.""",
        "error_types": ['throat_clearing', 'binding_language', 'vague_timeline'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """PRIVILEGED AND CONFIDENTIAL — ATTORNEY-CLIENT COMMUNICATION

To: John Smith (CEO), Mary Jones (CFO), Bob Lee (VP Operations), outside_vendor@contractor.com

Here is my legal advice regarding the pending regulatory matter...""",
        "error_types": ['privilege_waiver'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """On advice of counsel, our client has decided not to respond to your discovery requests at this time.""",
        "error_types": ['privilege_waiver', 'modal_verb_error'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Dear Opposing Counsel, this letter is to confirm that our client will not be available for the deposition scheduled for next Thursday. We need to reschedule. Please let me know your availability.""",
        "error_types": ['throat_clearing', 'nominalization', 'vague_timeline', 'modal_verb_error', 'ambiguity'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """We write to memorialize our understanding of the agreement reached between the parties during the phone call on February 14. The parties agreed that Plaintiff will dismiss the case with prejudice, that Defendant will pay $50,000 within 60 days, and that both parties will exchange mutual releases. Please sign below to confirm.""",
        "error_types": ['binding_language', 'subject_verb_agreement', 'modal_verb_error'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """The client wanted me to let you know that they are not happy with how this is going and thinks you should do something about it ASAP because the deadline is this week.""",
        "error_types": ['informal_language', 'vague_timeline', 'tone_adversarial'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """I wanted to reach out to touch base about the status of the matter. Hoping to hear from you soon!""",
        "error_types": ['informal_language', 'throat_clearing', 'tone_adversarial'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Without Prejudice

Dear Counsel, our client is open to settling this matter for the right number. We think somewhere in the $200,000 range would be appropriate. Let us know if this works.""",
        "error_types": ['vague_timeline', 'ambiguity'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Please find attached herewith the documents responsive to your request dated March 1, 2026, for your review and consideration. Do not hesitate to contact the undersigned if you have any questions or concerns regarding same.""",
        "error_types": ['informal_language', 'legalese', 'throat_clearing', 'archaic_language'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """This e-mail is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential, and exempt from disclosure under applicable law. If you are not the intended recipient, any use, dissemination, distribution, or copying of this communication is strictly prohibited.""",
        "error_types": ['privilege_waiver'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """My client rejects your settlement offer and we are prepared to go to trial on this matter. However, if you are willing to reconsider and come to the table with a more reasonable offer, we would be open to continuing settlement discussions.""",
        "error_types": ['informal_language', 'ambiguity'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """We apologize for any confusion that may have been caused by our previous correspondence.""",
        "error_types": ['modal_verb_error'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Kindly be informed that the above-captioned matter has been scheduled for a conference before the Honorable [Judge Name] on the 15th day of March, 2026, at the hour of 10:00 a.m., in Courtroom 4B.""",
        "error_types": ['legalese', 'throat_clearing', 'archaic_language'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """In the event that you fail to respond to this letter within ten (10) days of the date hereof, our client will have no choice but to pursue all available legal remedies.""",
        "error_types": ['vague_timeline', 'archaic_language'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Please be guided accordingly.""",
        "error_types": ['vague_timeline', 'govern_yourself'],
    },
    {
        "category": "email",
        "doc_subtype": "research_email",
        "text": """Our client strongly denies all allegations contained in your demand letter and reserves all rights.""",
        "error_types": ['vague_timeline', 'subject_verb_agreement', 'which_that'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """It is well-established that summary judgment is appropriate when there is no genuine dispute of material fact. Clearly, the facts here establish that no such dispute exists, as Defendant's own documents obviously confirm.""",
        "error_types": ['throat_clearing', 'overconfident'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Plaintiff respectfully submits that the motion should be denied for the following reasons. First, it is important to note that Defendant has failed to meet its burden. It bears emphasizing that the standard of review favors Plaintiff here.""",
        "error_types": ['contraction', 'throat_clearing'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Smith v. Jones, 123 F.3d 456, 459 (2nd Cir. 2001).""",
        "error_types": ['citation_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Id. at 459. The court further explained that... Id. at 461. However, Smith, 123 F.3d at 459, holds that...""",
        "error_types": ['vague_timeline', 'modal_verb_error', 'citation_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The motion was filed by Defendant. The brief was reviewed by the court. The standard was applied incorrectly by Plaintiff's counsel.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The Plaintiff, who is the party that brought this action against the Defendant, alleges that the Defendant, who is the corporate entity named in the caption, breached the contract, which was entered into on January 1, 2024, by failing to make payment.""",
        "error_types": ['defined_term_issue'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Defendant argues that the contract is unambiguous, and therefore extrinsic evidence should not be admitted, but Plaintiff contends that the contract is ambiguous, and therefore the court should admit extrinsic evidence to interpret the parties' intent.""",
        "error_types": ['vague_timeline'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """In Smith v. Jones, supra, the court held that...""",
        "error_types": ['citation_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """This case is about a breach of contract. The plaintiff is a company. The defendant is also a company. They entered into an agreement. The defendant did not fulfill its obligations.""",
        "error_types": ['vague_timeline'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The Court should also consider the fact that the Plaintiff made multiple attempts to resolve this dispute through informal negotiations, mediation, and had also proposed arbitration as an alternative, each of which was rejected by the Defendant without explanation.""",
        "error_types": ['informal_language', 'throat_clearing', 'nominalization', 'ambiguity', 'parallel_structure', 'which_that'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The data collected during the investigation show that Defendant's conduct, which constituted a material breach of the covenant of good faith and fair dealing which the parties agreed to uphold, was in direct violation of the agreement.""",
        "error_types": ['dangling_modifier', 'ambiguity', 'which_that'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """In conclusion, for all the foregoing reasons and for any additional reasons as the Court may determine, Plaintiff respectfully requests that this Honorable Court grant the instant motion.""",
        "error_types": ['legalese', 'vague_timeline', 'modal_verb_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Plaintiff's damages, which includes lost profits, consequential damages, and mitigation costs, was substantial.""",
        "error_types": ['subject_verb_agreement', 'which_that'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Being beyond any doubt insane at the time of the offense, the court ordered the defendant committed.""",
        "error_types": ['dangling_modifier', 'modal_verb_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Pursuant to Rule 56 of the Federal Rules of Civil Procedure, the defendant hereby moves this Court for an order granting summary judgment in favor of defendant and against plaintiff on all claims set forth in the complaint, and in support thereof respectfully shows the Court as follows...""",
        "error_types": ['legalese', 'archaic_language'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """Defendant's argument lacks merit. Plaintiff has thoroughly demonstrated, through extensive evidence and careful legal analysis, that the undisputed facts—which speak for themselves—clearly establish liability.""",
        "error_types": ['overconfident', 'which_that'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The Plaintiff argues that he was terminated based on race. The Defendant argues that the termination was performance-based. The Plaintiff has presented statistical evidence. The Defendant disputes this evidence.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """See, e.g., Smith v. Jones, 123 F.3d 456 (2d Cir. 2001); accord Brown v. Green, 234 F.3d 567 (9th Cir. 2002); but see White v. Black, 345 F.3d 678 (1st Cir. 2003).""",
        "error_types": ['citation_error'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """The defendant was arrested for fornicating under a little-used statute.""",
        "error_types": ['informal_language', 'dangling_modifier', 'ambiguity'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """It is arguable that the evidence will demonstrate that Defendant's actions were intentional and that they perhaps knew about the consequences before the breach occurred.""",
        "error_types": ['hedging', 'subject_verb_agreement'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """My client has discussed your proposal to fill the drainage ditch with his partners.""",
        "error_types": ['dangling_modifier'],
    },
    {
        "category": "brief",
        "doc_subtype": "research_brief",
        "text": """[A brief filed with the court contained the note:] PROBABLY NOT WORTH ARGUING???""",
        "error_types": ['tone_adversarial'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Vendor shall promptly notify the Client and/or its designated representative of any security breach.""",
        "error_types": ['modal_verb_error', 'ambiguity', 'defined_term_issue'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Vendor shall take commercially reasonable efforts to mitigate the impact of such breach within a reasonable time after discovery.""",
        "error_types": ['vague_timeline', 'modal_verb_error', 'defined_term_issue', 'efforts_standard'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Having been notified of the breach, remediation efforts shall commence immediately.""",
        "error_types": ['vague_timeline', 'modal_verb_error', 'defined_term_issue', 'efforts_standard'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Interest Rate shall mean a rate per annum of 9 percent.""",
        "error_types": ['modal_verb_error'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Company may not assign this Agreement without the prior written consent of the other Party, which consent shall not be unreasonably withheld.""",
        "error_types": ['modal_verb_error', 'ambiguity', 'which_that'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """WHEREAS, Party A is a Delaware corporation engaged in the business of software development; WHEREAS, Party B desires to license certain software from Party A; WHEREAS, the parties desire to set forth their respective rights and obligations herein; NOW THEREFORE, in consideration of the mutual promises and covenants contained herein, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the parties agree as follows:""",
        "error_types": ['legalese', 'subject_verb_agreement', 'ambiguity', 'archaic_language', 'which_that'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Client shall provide written notice of any breach within thirty (30) days of the occurrence of such breach, failing which the Client's right to claim breach shall be deemed waived.""",
        "error_types": ['modal_verb_error', 'archaic_language', 'which_that'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Licensor hereby grants to the Licensee a non-exclusive, non-transferable, limited, revocable license to use the Software.""",
        "error_types": ['legalese', 'archaic_language'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The parties agree that this Agreement shall be governed by and construed in accordance with the laws of the State of New York, without giving effect to any choice of law or conflict of law rules or provisions.""",
        "error_types": ['redundant_doublet', 'modal_verb_error'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Vendor agrees to indemnify Client for all losses, damages, costs and expenses arising from or related to any breach of this Section, including attorney's fees.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Confidential Information shall be used solely and exclusively for the purposes set forth herein and for no other purpose whatsoever.""",
        "error_types": ['legalese', 'redundant_doublet', 'ambiguity'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The term 'Systems' includes all hardware, software, and network infrastructure provided by Vendor to client pursuant to this agreement, including any third-party components.""",
        "error_types": ['legalese', 'subject_verb_agreement', 'defined_term_issue'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Either party may terminate this Agreement for convenience upon reasonable notice.""",
        "error_types": ['vague_timeline', 'defined_term_issue'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The parties shall use their best efforts to obtain all necessary approvals, consents, and permits required in connection with the transactions contemplated by this Agreement.""",
        "error_types": ['informal_language', 'subject_verb_agreement', 'modal_verb_error', 'which_that', 'efforts_standard'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """WHEREAS, the Company shall provide quarterly financial reports to Investor by the 15th of each month following the calendar quarter.""",
        "error_types": ['subject_verb_agreement', 'ambiguity'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Agreement may not be modified or amended except by a writing signed by both parties, provided, however, that the parties may, by mutual agreement, waive this requirement.""",
        "error_types": ['vague_timeline', 'subject_verb_agreement', 'modal_verb_error', 'provided_however'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """The Contractor represents and warrants that it has the full right, power, authority, and capacity to enter into this Agreement.""",
        "error_types": ['represents_warrants'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Time is of the essence with respect to all dates and deadlines set forth in or referred to in this Agreement.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """In the event of any dispute, controversy, or claim arising out of or relating to this Agreement, or the breach, termination, or invalidity thereof, the parties shall negotiate in good faith to resolve such dispute for a period of thirty (30) days.""",
        "error_types": ['archaic_language'],
    },
    {
        "category": "contract",
        "doc_subtype": "research_contract",
        "text": """Notwithstanding anything herein to the contrary, the provisions of Sections 5, 7, and 14 shall survive the termination or expiration of this Agreement.""",
        "error_types": ['legalese', 'modal_verb_error', 'ambiguity'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Witnesseth: THAT the party of the first part, hereinafter referred to as 'Lessor,' for and in consideration of the covenants and agreements herein contained and the payment of rent as herein provided, does hereby lease unto the party of the second part, hereinafter referred to as 'Lessee'...""",
        "error_types": ['legalese', 'redundant_doublet', 'ambiguity', 'defined_term_issue', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The aforementioned party (hereinafter 'Defendant') did theretofore engage in conduct violative of the abovementioned statute.""",
        "error_types": ['legalese', 'defined_term_issue', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The lessee shall make payment of rent in the sum of Two Thousand Dollars ($2,000.00) on the first day of each calendar month pursuant to the terms and conditions of this lease agreement.""",
        "error_types": ['legalese', 'nominalization', 'redundant_doublet'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Be it known to all men by these presents that...""",
        "error_types": ['throat_clearing', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """In the event that the lessee fails to make timely payment of rent, the lessor shall have the right to exercise any and all remedies available under applicable law.""",
        "error_types": ['informal_language', 'nominalization', 'redundant_doublet', 'vague_timeline', 'modal_verb_error'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Prior to the commencement of the work, the Contractor shall obtain all necessary permits.""",
        "error_types": ['legalese', 'nominalization', 'vague_timeline'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The parties desire to set forth herein their mutual understanding with respect to the subject matter hereof.""",
        "error_types": ['legalese', 'nominalization', 'subject_verb_agreement', 'ambiguity', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The undersigned hereby acknowledges receipt of the foregoing and agrees to be bound by the terms and conditions set forth hereinabove.""",
        "error_types": ['legalese', 'ambiguity', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Null and void" / "cease and desist" / "terms and conditions" / "any and all" / "due and payable" / "full and complete" / "true and correct""",
        "error_types": ['redundant_doublet'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Said agreement" / "said party" / "said document""",
        "error_types": ['legalese', 'subject_verb_agreement', 'ambiguity', 'archaic_language', 'which_that'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The Employer reserves the right, at its sole and exclusive discretion, to modify, alter, change, or amend these policies at any time, with or without notice, for any reason or no reason whatsoever.""",
        "error_types": ['redundant_doublet', 'modal_verb_error'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """In witness whereof, the parties hereto have executed this Agreement as of the day and year first above written.""",
        "error_types": ['archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """It is the intention of the parties that the provisions hereof be interpreted in a manner consistent with the intent of the parties.""",
        "error_types": ['throat_clearing', 'nominalization', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Notwithstanding the foregoing, and without limiting the generality of the provisions contained hereinabove or hereinbelow...""",
        "error_types": ['legalese', 'ambiguity', 'archaic_language'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Each Party shall have the obligation to indemnify, defend, save and hold harmless the other Party from and against any and all claims...""",
        "error_types": ['nominalization', 'redundant_doublet', 'modal_verb_error'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The Contractor agrees to perform the work in a good and workmanlike manner.""",
        "error_types": ['redundant_doublet', 'defined_term_issue'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """To the extent permitted by applicable law, and subject to the limitations set forth herein, including without limitation those set forth in Section 12...""",
        "error_types": ['legalese', 'binding_language', 'vague_timeline'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The parties acknowledge and agree that time is of the essence with respect to each and every obligation, date, deadline, term, condition, and requirement set forth in this Agreement.""",
        "error_types": ['redundant_doublet'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """Nothing in this Agreement shall be construed to limit or restrict in any way the rights, remedies, or other recourse of any party under applicable law.""",
        "error_types": ['throat_clearing', 'redundant_doublet', 'subject_verb_agreement', 'modal_verb_error', 'which_that'],
    },
    {
        "category": "plain",
        "doc_subtype": "research_plain",
        "text": """The parties hereto agree that, pursuant to and in accordance with the terms, conditions, and provisions of this Agreement and applicable law, Vendor shall effectuate delivery of the goods.""",
        "error_types": ['legalese', 'nominalization', 'redundant_doublet', 'modal_verb_error', 'archaic_language'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The prosecutor's expectation was that defense counsel would make an objection to the evidence.""",
        "error_types": ['nominalization'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """There is an agreement between the two parties for a settlement of $1 million.""",
        "error_types": ['subject_verb_agreement'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The plaintiff made a determination that the defendant's conduct was in violation of the contract.""",
        "error_types": ['nominalization'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """It is the position of the plaintiff that the defendant's failure to make payment constitutes a breach.""",
        "error_types": ['nominalization'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The company conducted an investigation of the incident and made a recommendation for the implementation of new safety procedures.""",
        "error_types": ['nominalization'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """Plaintiff's damages, which includes lost profits, consequential damages, and the costs of mitigation, was substantial.""",
        "error_types": ['subject_verb_agreement', 'modal_verb_error', 'which_that'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """Each of the defendants were found liable by the jury.""",
        "error_types": ['passive_voice'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The court's holding in Smith v. Jones, which was decided in 2001, which established a new standard for causation, which has since been applied in over 50 cases...""",
        "error_types": ['informal_language', 'ambiguity', 'which_that'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """Having reviewed the complaint, the motion to dismiss was filed.""",
        "error_types": ['vague_timeline', 'dangling_modifier', 'modal_verb_error'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The attorney, after filing the brief, reviewing the record, and having conducted three client interviews, prepared the motion.""",
        "error_types": ['modal_verb_error', 'parallel_structure'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The judge stated that the defendant's conduct was inappropriate, citing numerous violations, that had alarmed the court, and recommending enhanced sentencing.""",
        "error_types": ['parallel_structure'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The plaintiff only relied on three cases in its brief.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The evidence is clear: the defendant drove recklessly, ran a red light, and had been drinking alcoholic beverages prior to the accident.""",
        "error_types": ['parallel_structure'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """Pursuant to our discussions, it is our understanding that your client may possibly be willing to consider the potential option of settling.""",
        "error_types": ['nominalization', 'hedging', 'modal_verb_error'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The data shows that defendant's conduct was in violation of the statute.""",
        "error_types": ['informal_language'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The court will hear argument on Monday concerning whether Plaintiff's filing was timely, which was submitted last Tuesday.""",
        "error_types": ['dangling_modifier', 'which_that'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The defendant was sentenced to five years in prison under the statute providing for enhanced penalties for repeat offenders who have committed prior offenses.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The issue before this Court is whether or not the statute's application to these facts constitutes a violation of the plaintiff's due process rights.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The contract, which the parties entered into in January, which required monthly payments, which were due on the first of the month, was breached.""",
        "error_types": ['informal_language', 'passive_voice', 'which_that'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """The firm represents clients in matters involving disputes related to issues concerning employment law.""",
        "error_types": ['style_issue'],
    },
    {
        "category": "grammar",
        "doc_subtype": "research_grammar",
        "text": """It is arguable that the evidence perhaps demonstrates that the defendant may have known about the possible consequences of their alleged actions.""",
        "error_types": ['hedging', 'subject_verb_agreement', 'modal_verb_error'],
    },
]
